### ISSUE TITLE
깃헙 액션 - 클스챌 완료 이슈 생성시

### ISSUE THREAD

**Issue by justinyoo** [hackersground-kr/operations#8]
## 요구사항

  1. 이슈 생성 트리거로만 작동 👉 [`issues/opened`](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues)
  2. `csc` 레이블과 `xx-900` 레이블 추가
  3. `verifying` 레이블 추가
  4. 확인자 리스트에서 랜덤으로 한사람 할당
  5. 이슈 코멘트 남기기 👉 "곧 확인하겠습니다"

## 컨셉 플로우차트

```mermaid
flowchart TD

start_process(("시작"))
issue_created["'이슈 생성' 트리거"]
check_issue["이슈 확인"]
is_valid_issue{"유효한 이슈인가?"}
assign_assignee["확인자 랜덤 할당"]
add_label["레이블 3개 추가: 'csc', `veritying`, 'az-900'|'az-900'|'ai-900'|'dp-900'|'pl-900'|'sc-900'|'ms-900'"]
add_comment["코멘트 남기기 👉 '곧 확인하겠습니다'"]
end_process(("종료"))

start_process --> issue_created --> check_issue --> is_valid_issue
is_valid_issue -- 예 --> assign_assignee
is_valid_issue -- 아니오 --> end_process
assign_assignee --> add_label --> add_comment --> end_process
```

**Comment by hyewonm** [comment]
@justinyoo 

![Image](https://github.com/hackersground-kr/operations/assets/42796947/e58e44a9-4730-40e6-85e6-cc40b5936498)

본문에서 MSlearnProfile 받아오는 코드 추가해야합니다
